DROP TABLE IF EXISTS `petshop`;
CREATE TABLE `petshop` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` tinytext NOT NULL,
  `description` text NOT NULL,
  `img_path` tinytext NOT NULL,
  `link` tinytext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `petshop` (`id`, `name`, `description`, `img_path`, `link`) VALUES
(NULL,	'Bulldog',	'Bulldogs originally were used to drive cattle to market and to compete in a bloody sport called bullbaiting. Today, they\'re gentle companions who love kids. A brief walk and a nap on the sofa is just this dog breed\'s speed.\r\n',	'bulldog.jpg',	NULL),
(NULL,	'American Pit Bull Terrier',	'The American Pit Bull Terrier is a companion and family dog breed. Originally bred to \"bait\" bulls, the breed evolved into all-around farm dogs, and later moved into the house to become \"nanny dogs\" because they were so gentle around children. Their tenacity, gameness, and courage make them popular competitors in the sports of weight pulling, agility, and obedience competition.',	'americanpitbull.jpg',NULL),
(NULL,	'Collie',	'The Collie dog breed is a native of Scotland, mostly of the Highland regions but also bred in the Scottish Lowlands and northern England, where she was used primarily as a herding dog. She is a sensitive and intelligent dog, known for her undying loyalty and amazing ability to foresee her owner\'s needs. She is a great family companion, and is still a capable herding dog.',	'collie.jpg',	NULL),
(NULL,	'Dalmatian',	'Best known as the star of Disney\'s 101 Dalmatians, this sleek and athletic dog breed has a history that goes back several hundred years. He started out as a coach dog but has also served in many other capacities, including hunter, firehouse dog, and circus performer. As charming in life as in film, he goes from gallant to goofy to gallant again in the blink of an eye, and loves to be a part of everything his family does.',	'dalmatian.jpg',NULL),
(NULL,	'French Bulldog',	'The French Bulldog has enjoyed a long history as a companion dog. Created in England to be a miniature Bulldog, he accompanied English lacemakers to France, where he acquired his Frenchie moniker. Besides being a companion, he once served as an excellent ratter, but today his job focuses on being a fabulous family friend and show dog. He\'s a rare dog breed, so expect to put in some time on a waiting list before you\'re able to bring one home.',	'french-bulldog.jpg',	NULL),
(NULL,	'German Shepherd Dog',	'The German Shepherd Dog is one of America\'s most popular dog breeds — for good reason. He\'s an intelligent and capable working dog. His devotion and courage are unmatched. And he\'s amazingly versatile, excelling at most anything he\'s trained to do: guide and assistance work for the handicapped, police and military service, herding, search and rescue, drug detection, competitive obedience and, last but not least, faithful companion.',	'german-shepherd-dog.jpg',	NULL),
(NULL,	'Pug',	'Pugs often are described as a lot of dog in a small space. These sturdy, compact dogs are a part of the American Kennel Club\'s Toy group, and are known as the clowns of the canine world because they have a great sense of humor and like to show off. Originally bred to be a lap dog, the Pug thrives on human companionship.',	'pug.jpg',	NULL),
(NULL,	'Rottweiler',	'Rottweilers were originally dogs bred to drive cattle to market. Later they were used to pull carts for butchers. They were among the earliest police dogs and serve with honor in the military. Most important, they are popular family guardians and friends.',	'rottweiler.jpg',	NULL),
(NULL,	'Yorkipoo',	'A fun-loving \"designer dog\" — and therefore a mixed dog breed — a Yorkipoo is a cross between the Yorkshire Terrier and a Toy or Miniature Poodle. Intelligent, affectionate, and gentle, he makes a delightful companion and is perfectly suited to apartment life, especially if you don\'t mind the barking. He has plenty of energy to be burned off and he loves to play when he\'s not parked on your lap watching the world go by. His ability to run fast and jump high can be surprising to those who aren\'t expecting a canine Superman in miniature.',	'yorkipoo.jpg',	NULL),
(NULL,	'Kuvasz',	'The Kuvasz is a large, white flock-guarding dog who hails from Hungary. A one-family dog, he\'s protective of his people and suspicious of strangers. The Kuvasz thinks for himself and can be challenging to train.',	'kuvasz.jpg',	NULL),
(NULL,	'American Bobtail Cat',	'While the breed is still developing, breeders say that Bobtails are playful, energetic, and friendly, and possess an uncanny intelligence for Houdini-type escapes from closed rooms and fastened cages. Very people-oriented, they are not above demanding human attention by meowing or commandeering available laps.',	'american-bobtail.jpg',	NULL),
(NULL,	'British Shorthair Cat',	'If you\'re looking for a cat that will loot your refrigerator and swing dizzily from your chandeliers, then the British Shorthair is not for you. Brits are quiet, even-tempered, undemanding cats with a bit of typical British reserve, particularly when they\'re first introduced. When they get over their initial shyness, however, they become extremely faithful companions. British Shorthairs tend to show their loyalty to the entire family rather than select one person with whom to bond. British Shorthair breeders describe Brits as cats that like to keep a low profile, sweet and affectionate but not clingy \'in-your-face\' type cats. They tend to be independent and if left on their own can usually adapt quite well.',	'british-shorthair.jpg',	NULL),
(NULL,	'Cymric Cat',	'The personality of the Cymric has won a strong following despite the breeding challenges. Cymrics are intelligent, fun-loving cats, and they get along well with other pets, including dogs. Cymrics are particularly noted for their loyalty to their humans and enjoy spending quality time with them. As cats go, they can be easily taught tricks. Despite their playful temperament, they are gentle and nonaggressive. Their playful yet tractable dispositions are good for families with children.',	'cymric.jpg',	NULL),
(NULL,	'Exotic Shorthair Cat',	'Some folks who don\'t appreciate that laid-back, mellow personality label Persians and their relatives \'furniture with fur\', but in truth Exotics are playful and enjoy a good game of catching the catnip mouse between bouts of catching a few ZZZs. Because of the American Shorthair influence, Exotics are reported to be livelier than Persians, although some breeders say that the two breeds are very similar in temperament.',	'exotic-shorthair.jpg',	NULL),
(NULL,	'Himalayan Cat',	'Himmies, as fanciers call them, are perfect indoor cat companions. They are gentle, calm, and sweet-tempered, but they possess a playful side as well. Like the Siamese, Himalayans love to play fetch, and a scrap of crumpled paper or a kitty toy will entertain them for hours.',	'himalayan.jpg',	NULL),
(NULL,	'Munchkin Cat',	'For their part, Munchkins, oblivious to the controversy surrounding them, go on being just what they are, cats; self-assured and outgoing. They love to wrestle and play with their long-legged feline friends, happily unaware that there\'s anything different about them. Nor do their feline companions treat them like members of the vertically challenged. Only humans look at them askance.',	'munchkin.jpg',	NULL),
(NULL,	'Scottish Fold Cat',	'Scottish Folds are intelligent, sweet-tempered, soft-spoken, and easily adaptable to new people and situations. They are very loyal and tend to bond with one person in the household. While they will usually allow others to cuddle and pet them, their primary attachment becomes quickly clear as they single out their chosen humans. They thrive on attention, but it must be on their own terms.',	'scottish-fold.jpg',	NULL),
(NULL,	'Siberian Cat',	'Siberians are affectionate cats with a good dose of personality and playfulness. They are amenable to handling, and breeders note that Siberians have a fascination with water, often dropping toys into their water dishes or investigating bathtubs before they\'re dry. Siberians seem very intelligent, with the ability to problem-solve to get what they want. Despite their size, they are very agile and are great jumpers, able to leap tall bookcases in a single bound.',	'siberian.jpg',	NULL),
(NULL,	'Snowshoe Cat',	'Breeders brave enough to take on the Snowshoe challenge find that the cat pays back the effort in love and affection. Anyone looking for an aloof, standoffish cat need not apply for Snowshoe ownership, fanciers claim that Snowshoes don\'t realize that they\'re cats; they consider themselves people. They love to touch and be touched. Very intelligent, they can be taught a number of tricks. Snowshoes are also known for their fascination with water and on occasion will climb into the tub for a swim, as long as it\'s their idea. While not as loud or vocal as the Siamese, Snowshoes are never at a loss for words.',	'snowshoe.jpg',	NULL),
(NULL,	'Turkish Angora Cat',	'Turkish Angora fanciers are as attached to their cats as their cats are to them. Angoras seem to invoke strong responses in their humans with their symmetry, intelligence, and devotion to their humans. Angoras bond with their families completely; an Angora is not happy unless he is right in the middle of whatever you\'re doing. They enjoy a good conversation and can keep up their end of the discussion with the best of them. Angoras are good-natured, but determined. Once an Angora gets an idea into his head, you might as well just give in and spare yourself the lengthy argument.',	'turkish-angora.jpg',	NULL);
